=== apache/stratos/components/org.apache.stratos.manager.console/console/controllers/forms/schema/configure/application-policies.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "root",
    "type": "object",
    "title": "Application Policy Definition",
    "name": "Application Policy",
    "options": {
        "disable_properties": true,
        "disable_collapse": true
    },
    "properties": {
        "id": {
            "id": "root/id",
            "type": "string",
            "title": "Application Policy Id ",
            "name": "Application Policy Id"
        },
        "algorithm": {
            "id": "root/algorithm",
            "type": "string",
            "title": "Application Policy Algorithm ",
            "name": "Application Policy Algorithm",
            "enum": ["one-after-another","all-at-once"]
        },
        "networkPartitions": {
            "id": "root/networkPartitions",
            "type": "array",
            "title": "Network Partitions ",
            "name": "Network Partitions",
            "format":"tabs",
            "items": {
                "id": "root/networkPartitions/0",
                "type": "string",
                "title": "Network Partitions ",
                "name": "Network Partitions"
            }
        },
        "properties": {
            "id": "root/properties",
            "type": "array",
            "title": "Properties",
            "format": "tabs",
            "items": {
                "id": "root/properties/0",
                "type": "object",
                "title": "Property",
                "properties": {
                    "name": {
                        "id": "root/properties/0/name",
                        "title": "Name",
                        "type": "string"
                    },
                    "value": {
                        "id": "root/properties/0/value",
                        "title": "Value",
                        "type": "string"
                    }
                }
            }
        }
    },
    "required": [
        "id",
        "algorithm",
        "networkPartitions",
        "properties"
    ]
}

=== apache/stratos/samples/application-policies/application-policy-3.json
{
    "id": "application-policy-3",
    "algorithm":"one-after-another",
    "networkPartitions":[
        "network-partition-1",
        "network-partition-2",
        "network-partition-3",
        "network-partition-4",
        "network-partition-5"
    ],
    "properties":[
        {
            "name": "network-partition-groups",
            "value": "network-partition-1|network-partition-2, network-partition-3, network-partition-4|network-partition-5"
        }
    ]
}

=== apache/stratos/samples/application-policies/application-policy-2.json
{
    "id": "application-policy-2",
    "algorithm":"all-at-once",
    "networkPartitions":[
        "network-partition-3"
    ],
    "properties":[
        {
            "name": "key-1",
            "value": "value-1"
        },
        {
            "name": "key-2",
            "value": "value-2"
        }
    ]
}

=== apache/stratos/components/org.apache.stratos.manager.console/console/controllers/forms/default/applications/applicationpolicies.json
{
    "id": "application-policy-1",
    "algorithm":"one-after-another",
    "networkPartitions":[
        "network-partition-1"
    ],
    "properties":[
        {
            "name": "key-1",
            "value": "value-1"
        },
        {
            "name": "key-2",
            "value": "value-2"
        }
    ]
}
