=== apache/stratos/components/org.apache.stratos.manager.console/console/controllers/forms/schema/configure/autoscalingpolicies.json
{
    "type":"object",
    "$schema": "http://json-schema.org/draft-04/schema",
    "id": "root",
    "title":"Auto Scaling Policy Definition",
    "name": "Auto Scaling Policy",
    "options": {
        "disable_properties": true,
        "disable_collapse": true
    },
    "required" : ["id", "loadThresholds"],
    "properties":{
        "id": {
            "type":"string",
            "id": "root/id",
            "title":"Auto Scale policy ID",
            "minLength":4,
            "default":"Policy name",
            "maxItems":1
        },
        "description": {
            "type":"string",
            "id": "root/description",
            "title": "Description",
            "name": "Description",
            "maxItems":1
        },
        "isPublic": {
            "type":"boolean",
            "id": "root/isPublic",
            "title": "Is Public",
            "name": "Is Public",
            "default": false,
            "maxItems":1
        },
        "loadThresholds": {
            "type":"object",
            "title":"Load Thresholds",
            "id": "root/loadThresholds",
            "required":["loadAverage","memoryConsumption","requestsInFlight"],
            "options": {
                "disable_properties": true
            },
            "properties":{
                "requestsInFlight": {
                    "type":"object",
                    "id": "root/loadThresholds/requestsInFlight",
                    "title": "Requests In Flight",
                    "name": "Requests In Flight",
                    "format": "grid",
                    "options": {
                        "disable_properties": true,
                        "collapsed": false
                    },
                    "properties":{
                        "lowerLimit": {
                            "type":"number",
                            "id": "root/loadThresholds/requestsInFlight/lowerLimit",
                            "title": "Lower Limit",
                            "name": "Lower Limit",
                            "default":5,
                            "format": "number",
                            "required":false
                        },
                        "upperLimit": {
                            "type":"number",
                            "id": "root/loadThresholds/requestsInFlight/upperLimit",
                            "title": "Upper Limit",
                            "name": "Upper Limit",
                            "default":30,
                            "format": "number",
                            "required":false
                        }
                    }
                },
                "memoryConsumption": {
                    "type":"object",
                    "id": "root/loadThresholds/memoryConsumption",
                    "title": "Memory Consumption",
                    "name": "Memory Consumption",
                    "format": "grid",
                    "options": {
                        "disable_properties": true,
                        "collapsed": false
                    },
                    "properties":{
                        "lowerLimit": {
                            "type":"number",
                            "id": "root/loadThresholds/memoryConsumption/lowerLimit",
                            "title": "Lower Limit",
                            "name": "Lower Limit",
                            "default":50,
                            "format": "number",
                            "required":false
                        },
                        "upperLimit": {
                            "type":"number",
                            "id": "root/loadThresholds/memoryConsumption/upperLimit",
                            "title": "Upper Limit",
                            "name": "Upper Limit",
                            "default":80,
                            "format": "number",
                            "required":false
                        }
                    }
                },
                "loadAverage": {
                    "type":"object",
                    "id": "root/loadThresholds/loadAverage",
                    "title": "Load Average",
                    "name": "Load Average",
                    "format": "grid",
                    "options": {
                        "disable_properties": true,
                        "collapsed": false
                    },
                    "properties":{
                        "lowerLimit": {
                            "type":"number",
                            "id": "root/loadThresholds/loadAverage/lowerLimit",
                            "title": "Lower Limit",
                            "name": "Lower Limit",
                            "default":20,
                            "format": "number",
                            "required":false
                        },
                        "upperLimit": {
                            "type":"number",
                            "id": "root/loadThresholds/loadAverage/upperLimit",
                            "title": "Upper Limit",
                            "name": "Upper Limit",
                            "default":100,
                            "format": "number",
                            "required":false
                        }
                    }
                }


            }
        }
    }
}

=== apache/stratos/components/org.apache.stratos.manager.console/console/controllers/forms/default/configure/autoscalingpolicies.json
{
    "id": "economy",
    "description":"autoscale policy description",
    "isPublic":false,
    "loadThresholds": {
        "requestsInFlight": {
            "upperLimit": 30,
            "lowerLimit": 5
        },
        "memoryConsumption": {
            "upperLimit": 80,
            "lowerLimit": 50
        },
        "loadAverage": {
            "upperLimit": 100,
            "lowerLimit": 20
        }
    }
}
