=== apache/stratos/components/org.apache.stratos.manager.console/console/controllers/forms/schema/configure/partitions.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "root",
    "type": "object",
    "title": "Network Partition Definition",
    "name": "Network Partition Policy",
    "options": {
        "disable_properties": true,
        "disable_collapse": true
    },
    "properties": {
        "id": {
            "id": "root/id",
            "type": "string",
            "title": "Network Partition Id"
        },
        "provider": {
            "id": "root/provider",
            "type": "string",
            "title": "Network Partition provider",
            "enum": ["mock", "ec2", "openstack", "kubernetes", "gce"]
        },
        "partitions": {
            "id": "root/partitions",
            "type": "array",
            "format": "tabs",
            "title": "Partitions",
            "items": {
                "id": "root/partitions/0",
                "type": "object",
                "title": "Partition",
                "properties": {
                    "id": {
                        "id": "root/partitions/0/id",
                        "type": "string",
                        "title": "Partition Id"
                    },
                    "property": {
                        "id": "root/partitions/0/property",
                        "type": "array",
                        "title": "Property",
                        "format": "tabs",
                        "items": {
                            "id": "root/partitions/0/property/0",
                            "type": "object",
                            "title": "Property",
                            "properties": {
                                "name": {
                                    "id": "root/partitions/0/property/0/name",
                                    "title": "Name",
                                    "type": "string"
                                },
                                "value": {
                                    "id": "root/partitions/0/property/0/value",
                                    "title": "Value",
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "properties": {
            "id": "root/properties",
            "type": "array",
            "title": "Properties",
            "format": "tabs",
            "items": {
                "id": "root/properties/0",
                "type": "object",
                "title": "Property",
                "properties": {
                    "name": {
                        "id": "root/properties/0/name",
                        "title": "Name",
                        "type": "string"
                    },
                    "value": {
                        "id": "root/properties/0/value",
                        "title": "Value",
                        "type": "string"
                    }
                }
            }
        }
    },

    "required": [
        "id",
        "partitions",
        "provider"
    ]
}

=== apache/stratos/components/org.apache.stratos.manager.console/console/controllers/forms/default/configure/partitions.json
{
    "id": "network-partition-1",
    "provider": "mock",
    "partitions": [
        {
            "id": "partition-1",
            "property": [
                {
                    "name": "region",
                    "value": "default"
                }
            ]
        }
    ],
    "properties": [
    ]
}
